### ISSUE TITLE
Dúvida sobre linguagem.

### ISSUE THREAD

**Issue by camilotx** [ShopBackBR/RecognizerLinkChallenge#1]
Há alguma preferencia de linguagem? PHP, Python, C++ ou Java?

**Comment by RafaelPlantard** [comment]
Nossa preferência é PHP, mas o que queremos mesmo é entender sua lógica de programação acima da linguagem que adotará, por exemplo, eu fiz o desafio em Swift, usando o Playground... A linguagem para nós é somente uma ferramenta, o mais importante sempre é a pessoa.
