### ISSUE TITLE
Duvida sobre a estrutura do banco de dados

### ISSUE THREAD

**Issue by lagoafilipe85** [ShopBackBR/RecognizerLinkChallenge#2]
Olá.
tenho uma duvida na estrutura do banco de dados. A duvida é:
Baseando que vocês utilizam o sgbd mongodb, cada loja tem um banco de dados, ou elas estão em um único banco separado por coleção ou tudo em um único banco de dados e uma única coleção?

**Comment by RafaelPlantard** [comment]
Qual seria sua solução?
Temos os dois casos, mas queremos saber como também você resolveria.
Okay?
